# Generated by Django 4.2.17 on 2025-01-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plan',
            field=models.CharField(choices=[('free', 'Grátis'), ('basic', 'Básico'), ('premium', 'Premium'), ('enterprise', 'Empresarial')], default='free', max_length=20),
        ),
    ]
