# Generated by Django 4.2.17 on 2025-02-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapa', '0005_weatherdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherdata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='temperature',
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='data',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='city',
            field=models.CharField(max_length=100),
        ),
    ]
